add fancy travelnet (textures by @El-Naso)
mt-mods/travelnet pull request #15
Opened 2021-06-03 12:18 UTC by BuckarooBanzay

Replaces https://github.com/pandorabox-io/pandorabox-textures/pull/3

2021-06-03 19:34 UTC, Panquesito7 commented on README.md
> +* `textures/travelnet_fancy*` [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) provided by @El-Naso
```suggestion
* `textures/travelnet_fancy_*.png` [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) provided by @El-Naso
```

2021-06-03 19:34 UTC, Panquesito7 commented on travelnet.lua
> +	inventory_image = "travelnet_inv_base.png", --TODO: proper inv
```suggestion
	inventory_image = "travelnet_inv_base.png", -- TODO: proper inv
```

2022-01-14 16:41 UTC, Panquesito7 requested changes
There are [**merge conflicts**](https://github.com/mt-mods/travelnet/pull/15/conflicts). Could you please fix the error? If you don't have time available, I could work on it if wanted. Thanks. 🙂

2022-01-14 17:34 UTC, BuckarooBanzay commented
> There are [**merge conflicts**](https://github.com/mt-mods/travelnet/pull/15/conflicts). Could you please fix the error? If you don't have time available, I could work on it if wanted. Thanks. slightly_smiling_face

I initially just dumped this here because i didn't have an idea on how to fit these textures into the existing mod.
A new box perhaps with a "fancy" recipe? Not sure but i'm open for ideas ;)

2022-01-15 03:18 UTC, OgelGames commented
Seeing as there is now an API to register travelnet nodes, I think it would make more sense for it to be a separate mod.

https://github.com/mt-mods/travelnet/blob/master/doc/api.md#fully-custom-nodes

2022-01-28 20:29 UTC, wsor4035 commented
closed by https://github.com/mt-mods/fancy_travelnet

2022-01-28 20:29 UTC, closed without merging