Document settings in README
mt-mods/travelnet pull request #61
Opened 2022-09-25 11:54 UTC by cweiske

.. so they are discoverable without having to read the source code

2022-09-25 14:33 UTC, wsor4035 approved these changes

2022-09-25 14:33 UTC, wsor4035 requested changes
currently, this is pointless, the descriptions should be improved in https://github.com/mt-mods/travelnet/blob/master/settingtypes.txt and linked to. no point in duplicating information that will fall out of date

2022-09-26 18:29 UTC, cweiske commented
I've modified settingstypes.txt and linked it from the readme.

2022-09-26 22:28 UTC, wsor4035 approved these changes

2022-09-26 22:28 UTC, merged