MineClone 2 adjustments
mt-mods/travelnet pull request #63
Opened 2022-09-25 12:02 UTC by cweiske

- Do not use the wooden box texture for travelnet boxes
- Use nearly the same ingredients for boxes (diamond block instead of mese)
- Enable doors

2022-09-25 14:53 UTC, wsor4035 requested changes
> diamond might be a bit expensive compared to mese which is quite abundant in mtg and even spawns as blocks (maybe redtsoneblock instead?)

from the mcl discord, and i agree with it

2022-09-26 04:11 UTC, cweiske commented
I've replaced the diamond block with a redstone block.

2022-09-26 04:13 UTC, wsor4035 approved these changes

2022-09-26 04:13 UTC, wsor4035 commented
will wait a bit to make sure no one else has any objections

2022-09-26 06:31 UTC, merged